name: tube-converter # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2023.4.0' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: tube-converter
summary: An easy-to-use YouTube video downloader # 79 char long summary
description: |
 * A basic yt-dlp frontend
 * Supports downloading videos in multiple formats (mp4, webm, mp3, opus, flac, and wav)
 * Run multiple downloads at a time
 * Supports downloading metadata and video subtitles
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
assumes:
  - snapd2.58
architectures:
  - amd64

layout:
  /usr/lib/org.nickvision.tubeconverter:
    symlink: $SNAP/usr/lib/org.nickvision.tubeconverter
  /usr/share/org.nickvision.tubeconverter:
    symlink: $SNAP/usr/share/org.nickvision.tubeconverter

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
package-repositories:
  - type: apt
    url: https://packages.microsoft.com/ubuntu/22.04/prod
    components: [main]
    suites: [jammy]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
  - type: apt
    components: [jammy]
    suites: [prebuilt-mpr]
    key-id: B70EAE798718E0FE2972DD0C4FE9F2C43D9428A0
    url: https://proget.makedeb.org
parts:
  libadwaita:
    source: https://gitlab.gnome.org/GNOME/libadwaita.git
    source-tag: '1.2.3'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dintrospection=enabled
      - -Dvapi=true
      - -Dtests=false
      - -Dexamples=false
    build-packages:
      - sassc
    override-pull: |
      craftctl default
      sed -e 's/-W\(format-nonliteral\)\b/-Wno-\1/g' -i meson.build
      patch -p1 < $CRAFT_PROJECT_DIR/patches/style-manager-Support-Yaru-accent-colors.patch
    prime:
      - usr/include
  yt-dlp:
    after: [libadwaita]
    # Missing optional dependencies atomicparsley, mpv, phantomjs and rtmpdump
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp.git
    source-tag: 2023.03.04
    python-packages:
      - pyxattr==0.7.2
      - PyGObject
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    override-pull: |
      craftctl default
      sed -i 's/^certifi\b/#\0/' requirements.txt
    prime:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
  ffmpeg:
    after: [ yt-dlp, libadwaita ]
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    prime:
      - -usr/include
  tube-converter:
    after: [ ffmpeg, yt-dlp, libadwaita ]
    plugin: dump
    source: https://github.com/nlogozzo/NickvisionTubeConverter.git
    source-type: git
    source-tag: snap-2023.4.0
    source-subdir: NickvisionTubeConverter.GNOME
    build-environment:
      - TC_PYTHON_SO: "/snap/tube-converter/current/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0"
    build-packages:
      - brotli
      - blueprint-compiler
      - just
      - dotnet-sdk-7.0
    stage-packages:
      - python3
      - libpython3.10
    override-pull: |
      craftctl default
      sed -e 's|Icon=org.nickvision.tubeconverter|Icon=/usr/share/icons/hicolor/scalable/apps/org.nickvision.tubeconverter.svg|' -i NickvisionTubeConverter.GNOME/org.nickvision.tubeconverter.desktop
    override-prime: |
      craftctl default
      cd ~/parts/tube-converter/src/NickvisionTubeConverter.GNOME
      just publish-self-contained /usr
      just install /root/prime
      sed -i "2 i export TC_PYTHON_SO=$TC_PYTHON_SO" $CRAFT_PRIME/usr/bin/org.nickvision.tubeconverter
      sed -i "s|Exec=/usr/bin/org.nickvision.tubeconverter --gapplication-service|Exec=/snap/tube-converter/current/usr/bin/org.nickvision.tubeconverter --gapplication-service|" $CRAFT_PRIME/usr/share/dbus-1/services/org.nickvision.tubeconverter.service
    prime:
      - usr/
    parse-info: [usr/share/metainfo/org.nickvision.tubeconverter.metainfo.xml]

slots:
  # for GtkApplication registration
  tube-converter:
    interface: dbus
    bus: session
    name: org.nickvision.tubeconverter    

apps:
  tube-converter:
    command: usr/bin/org.nickvision.tubeconverter
    extensions:
      - gnome
    common-id: org.nickvision.tubeconverter
    environment:
      TC_PYTHON_SO: /snap/tube-converter/current/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0
      GNOTIFICATION_BACKEND: freedesktop #This is to fix notifications
    desktop: usr/share/applications/org.nickvision.tubeconverter.desktop
    plugs:
      - home
      - network
      - network-status
      - removable-media
